### ISSUE TITLE
Change how stage features are exposed

### ISSUE THREAD

**Issue by TrevorFSmith** [mozilla/webxr-polyfill#12]
In AR, the idea that the local area consists of a flat floor (aka stage) will often not be true. In VR, the platforms may expose a stage center in the tracker coordinate system and may expose a 2D polygon that determines the clear space in which to move.

Expose a 'floor' XRAnchor that is always at floor level (as near as the platform can determine) underneath the current head pose.
Expose the VR style stage info (center point, polygon) through API on XRSession, and remove the 'stage' XRCoordinateSystem.
Update the examples to use the floor anchor.

**Comment by speigg** [comment]
The way I've thought of this is: for AR, the stage (or the stage "center"), can travel with the user. The exact behavior can be defined by the UA, but I imagine a type of "leashing", such that the stage center is fixed at an appropriate point on the floor near the user, until the user moves beyond a certain radius, at which point the stage is dragged along. This is similar to the way that I've seen virtual realities implemented for HoloLens.

**Comment by blairmacintyre** [comment]
When looking at what Hololens does, and to a certain extent what ARKit and ARCore do (no notion of stage, just anchors), compared to systems that have a notion of a "stage" (e.g., fixed VR setups like Vive/Rift), it makes less sense to think of this as a "stage".  For example, in fixed VR, the user generally clears the floor of a room for the VR rig, and the "stage" actually does correspond to the physical area that the player can move.  In a mobile setup (both AR systems, and untethered VR such as the newer WindowsMR devices) the floor cannot be assumed to be flat.  So a "stage" means less.  More importantly, the idea of "attaching things to world near the user" can be done in other ways using anchors and other application specific code.

The thought with the "floor" is to have the UA make (at any point in time) it's best guess as to were the floor is under the user (some systems, such as those based on 3DOF VR or current ARCore/ARKit) might have to guess;  others might use the VR stage;  others (such as Hololens, that has a full mesh) might actually make a pretty good guess.  

A system that has a stage would expose that coordinate system.  On other systems, given a `floor`, the application can implement the idea of a "traveling stage" as they need.  I would imagine a simple demo system would have a method like `getOrCreateStage(): Anchor` to just retrieve a stage Anchor if it exists or create one based on the current value of the `floor`.  A more complex system would, as you say, move it with the user.

**Comment by TrevorFSmith** [comment]
Working on this in PR https://github.com/mozilla/webxr-polyfill/pull/29
