### ISSUE TITLE
[Bug] this._videoFrameCanvas is undefined

### ISSUE THREAD

**Issue by sumleo** [mozilla/webxr-polyfill#131]
It seems that all ar pages have this problem.

URL: https://examples.webxrexperiments.com/examples/ar_simplest/

Environment:
OS: Mac OS 10.14.4 (18E226)
Browser: Firefox 66.0.5 (64-bit)

Proven:
1.Normal case
![image](https://user-images.githubusercontent.com/29517764/58073749-07777d80-7bd6-11e9-9311-dfb81643029c.png)

2.After resize the window
![image](https://user-images.githubusercontent.com/29517764/58073779-1f4f0180-7bd6-11e9-9548-f6cbc7471528.png)

Reproduce:
1.Open the link with a small window size
2.Modify the window size

**Comment by blairmacintyre** [comment]
Fixed.  Note, this polyfill is no longer supported.  On the WebXR Viewer, we have developed a new JS api based on the emerging WebXR standard.  On desktop, the webRTC path was really just built to simplify debugging.
