### ISSUE TITLE
why does some examples don't work ?

### ISSUE THREAD

**Issue by pans0ul** [mozilla/webxr-polyfill#133]
Hi 
Im a newer to know about webxr-polyfill . Im excited to use webXR 

I tried these example on iphoneX  , IOS :11.4 ,browser :safiri ,and also tried these on Andriod phone system

the examples of url: 
https://examples.webxrexperiments.com/

but some examples ,including simplest AR ,Anchors, Hit testing ,Boombox,light,Image Detection wont show like picture that shows blew each examples .

For example I tried  : Anchors . the result show as blew : 

![image](https://user-images.githubusercontent.com/35412241/65756062-ef48d980-e146-11e9-92a3-75fa17d857a4.png)

is it need dependency to show correctly ?

thanks for all

**Comment by pans0ul** [comment]
is it based on ARkit or ARcore ?

**Comment by blairmacintyre** [comment]
This polyfill is deprecated;  it was designed to work in the experimental iOS app WebXR Viewer, and had "limited" support for other platforms (mostly to support some experiments we did, and debugged/developing).    None of the AR features (anchors, hit testing, etc) work anywhere except the WebXR Viewer, as they rely on that app implementation.

WebXR itself will be released on a number of browsers this fall.  The ongoing work is in github.com/immersive-web
