### ISSUE TITLE
Turn on the recording UI when on the iOS app

### ISSUE THREAD

**Issue by TrevorFSmith** [mozilla/webxr-polyfill#19]
Currently we don't pass the right flags so that when the user touches the eye icon they get access to the photo and video recording UI.

Pass the correct initialization flags to ARKit to turn on the recording UI.

**Comment by TrevorFSmith** [comment]
If the app passes in no options to ARKitWrapper.GetOrCreate then it defaults to showing the recording UI when the user triggers the "eye" icon.

**Comment by zoidhddhdd** [comment]
End
