### ISSUE TITLE
Consider renaming this repo to `webxr-polyfill`

### ISSUE THREAD

**Issue by dmarcos** [mozilla/webxr-polyfill#2]
And add an `examples` directory on it. I think is more important to emphasize the polyfill than the examples

**Comment by blairmacintyre** [comment]
I would second both of these request.  

FWIW, @dmarcos, we had talked about this at the start.  I'd proposed having the examples and the polyfill in separate repos, but was persuaded by the idea of one repo that people can fork and download and start playing, that includes the polyfill and examples.  

That said, I think we should entertain this suggestion, to make it clear that this is "polyfill first, examples second".  

I would go a bit further and ask if some of the files might be organized a bit more, even within the examples directory.

I get frustrated by projects like three.js, where all the examples are muddled into one huge directory.  When each example is precisely one file, that's fine, but when there is a pile of files and each example might be more than just the html file, it's hard to skim and understand what you need to poke at to get the full picture; which files are "support", which are "the two or three files for example1", "the two or three for example2", etc.

**Comment by TrevorFSmith** [comment]
Ok, the repo has been renamed and I'm rearranging the files now.

**Comment by TrevorFSmith** [comment]
Ok, the examples have been rearranged and the README expanded to say more about the polyfill status.
