### ISSUE TITLE
Fix grey flashing on tap in webkit

### ISSUE THREAD

**Issue by TrevorFSmith** [mozilla/webxr-polyfill#21]
Add -webkit-tap-highlight-color: rgba(0, 0, 0, 0) to the session layer's canvas to prevent the default webkit behavior of flashing grey on taps.

**Comment by blairmacintyre** [comment]
I think this also relates to selection of DOM elements.  There's a way to turn off selection of DOM content, zooming, etc. (I think it's "default behaviors" or something).  

We should probably consider not be using DOM elements in our samples/demos at all.  The "Anchors" demo has a DOM Button for adding the anchor.  If we are not allowing 2D elements in 3D, we should probably focus on using 3D content entirely, shouldn't we?  Supporting clicking on DOM elements, and overlaying DOM content on the 3D canvas, is probably going to hurt us in the long run.  

We will probably want to embed a 3D canvas into the DOM at some point in the future (e.g., the way the AFRame site does), but do we want to overlay the 3D canvas with a 3D canvas?  For example, that button won't show up if we "enter stereo" on a Daydream, etc.

**Comment by TrevorFSmith** [comment]
Showing DOM elements like buttons on top of the 3D and camera views is an app level decision. I agree that we should have example code that works across magic window, Cardboard, and HMDs, but for now the DOM elements make for easy to read sample code.
