### ISSUE TITLE
Where to host GA? (also: Enable GitHub Pages?)

### ISSUE THREAD

**Issue by cvan** [mozilla/webxr-polyfill#40]
Perhaps I’m unclear on how to load these examples outside the native apps. Is it helpful to have https://mozilla.github.io/webxr-polyfill/examples/ar_simplest.html, for example, be accessed by URL?

My reason for asking: @blairmacintyre wants Google Analytics to be added to the Polyfill.

1. From where should the GA JS snippets be hosted and loaded?
    - From the Polyfill.js script?
    - Are we looking for GA from third-party sites or for these examples only?
2. Would it be better to just add GA to the [test iOS app](https://github.com/mozilla-mobile/webxr-ios?files=1) to use [Google’s iOS GA SDK](https://developers.google.com/analytics/devguides/collection/ios/v3/)?

Let me know if I’m missing something. Thanks!

**Comment by blairmacintyre** [comment]
Hi Chris.  I don't want to track all uses of webxr, rather, I wanted to put the GA code in the top level page loaded by the iOS app, over in https://github.com/mozilla-mobile/webxr-ios

We may want to put it in the iOS app, eventually, but for now putting it in the top level page is easiest.  We don't want comprehensive telemetry yet, I just want to know if the app is being run.
