### ISSUE TITLE
Poor render quality on WebARonARCore viewer

### ISSUE THREAD

**Issue by andrelevi** [mozilla/webxr-polyfill#69]
When viewing the examples on the WebARCore viewer, it looks as though the rendering is upsampled with no AA:

[https://i.imgur.com/4bWInpK.jpg](https://i.imgur.com/4bWInpK.jpg)
[https://i.imgur.com/NGch3cl.jpg](https://i.imgur.com/NGch3cl.jpg)

Taken on a Galaxy S8.

**Comment by blairmacintyre** [comment]
Hmmm.  That looks terrible.  

My suspicion is that we're somehow rendering at a really low resolution.  I don't have an S8, so I can't check, but can you inspect the webview and see what the width/height of the canvas element is (not the style width, but the actual width).

We _should_ be using the CSS Width and Height, which is 360x740 for the S8 (see https://mydevice.io/devices/).  We do NOT use the devicePixelRatio (4 for the S8) which will result in it not using the full resolution (it will render at 360x740 and scale). 

But, this kind of aliasing is horrifyingly bad;  I can't imagine why it would look this way.  On my iPhone (which has a similar resolution and a ratio of 3) the 3D elements are a bit "soft" but don't show jaggies.

**Comment by blairmacintyre** [comment]
I will try this on my Pixel (once I get the app working).

**Comment by andrelevi** [comment]
I'm seeing a similar issue on desktop, where the canvas stays at the default 300x150 until the resize callback is called: https://github.com/mozilla/webxr-polyfill/blob/a7abb65f88347355010821b5096f305272b99619/polyfill/reality/CameraReality.js#L63.
The width/height attributes are then correctly updated to the window dimensions.

I'm guessing it's related and you are right about the canvas dimensions not being set correctly for the ARCore viewer.

**Comment by blairmacintyre** [comment]
Fixed, I think.
