### ISSUE TITLE
Undeclared variable _this in XRpolyfill.js

### ISSUE THREAD

**Issue by tbalouet** [mozilla/webxr-polyfill#83]
There's an undeclared variable which break apps from working here:
https://github.com/mozilla/webxr-polyfill/blob/master/polyfill/XRPolyfill.js#L92
![image](https://user-images.githubusercontent.com/5400381/36135162-adaf99d0-1089-11e8-9b63-87bd10a9a1e8.png)

**Comment by arturitu** [comment]
I think now is fixed. Thanks,

**Comment by tbalouet** [comment]
It is fixed in https://develop.examples.webxrexperiments.com/dist/webxr-polyfill.js but not the master branch, would be worth updating it as this thing breaks everything

**Comment by blairmacintyre** [comment]
Working now?  I merged all the branches recently when I did the 1.05 release of the browser.

**Comment by tbalouet** [comment]
Yes, everything's working now, thanks Blair!
